# Generated by Django 3.2.8 on 2022-06-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://website.com/', max_length=900)),
                ('menu_name', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://website.com/', max_length=900)),
                ('sub_menu_name', models.CharField(max_length=156)),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.topmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://website.com/', max_length=900)),
                ('product_name', models.CharField(max_length=156)),
                ('sub_menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.submenu')),
            ],
        ),
    ]
