# Generated by Django 3.2.8 on 2022-06-11 06:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220611_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=900)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='addional_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img1_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img2_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img3_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img4_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img5_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img6_alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='short_desc',
            field=models.TextField(blank=True, max_length=1156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sp',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='slug',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='topmenu',
            name='slug',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='product.Color'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='product.Size'),
        ),
    ]
