# Generated by Django 3.2.8 on 2022-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220611_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=900)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='product.Tag'),
        ),
    ]
