# Generated by Django 3.2.8 on 2022-06-11 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220611_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='meta_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=900),
            preserve_default=False,
        ),
    ]
