# Generated by Django 3.2.8 on 2022-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220611_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='single_piece',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='in_stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
