# Generated by Django 3.2.8 on 2022-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220611_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
