# Generated by Django 3.2.8 on 2022-06-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_couponcode_couponcodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcodeusage',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.couponcode'),
        ),
    ]
