# Generated by Django 3.2.8 on 2022-06-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20220625_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.TextField(blank=True, max_length=11130, null=True),
        ),
    ]
