# Generated by Django 3.2.8 on 2022-06-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
