# Generated by Django 3.2.8 on 2023-01-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20230115_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='single_piece',
        ),
    ]
