# Generated by Django 3.2.8 on 2023-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20230115_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color_shade',
            field=models.ManyToManyField(blank=True, null=True, related_name='p_shade', to='product.Shade'),
        ),
        migrations.AddField(
            model_name='products',
            name='size_specification',
            field=models.ManyToManyField(blank=True, null=True, related_name='s_spec', to='product.Specification'),
        ),
    ]
