# Generated by Django 3.2.8 on 2023-02-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
