# Generated by Django 3.2.8 on 2023-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20230201_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='mrp',
        ),
        migrations.AddField(
            model_name='products',
            name='range_of',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
