# Generated by Django 3.2.8 on 2023-02-18 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
