# Generated by Django 3.2.8 on 2023-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
