# Generated by Django 4.0.4 on 2022-06-17 07:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://website.com/', max_length=900)),
                ('why_choose_us_img', models.ImageField(blank=True, null=True, upload_to='Page Data')),
                ('why_choose_us_img_1', models.ImageField(blank=True, null=True, upload_to='Page Data')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('fb', models.CharField(blank=True, max_length=156, null=True)),
                ('insta', models.CharField(blank=True, max_length=156, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=156, null=True)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://website.com/', max_length=900)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Page Data')),
                ('category', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('fb', models.CharField(max_length=156)),
                ('insta', models.CharField(max_length=156)),
                ('twitter', models.CharField(max_length=156)),
                ('youtube', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://thegrandindianroute.com/', max_length=900)),
                ('published', models.DateField()),
                ('updated', models.DateField(auto_now=True)),
                ('blog_banner_lg', models.ImageField(blank=True, null=True, upload_to='Page Data')),
                ('blog_banner_sm', models.ImageField(blank=True, null=True, upload_to='Page Data')),
                ('h1', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('edits', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ManyToManyField(to='blog.category')),
                ('tag', models.ManyToManyField(to='blog.tags')),
            ],
        ),
    ]
