# Generated by Django 4.0.4 on 2022-06-17 07:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='page_name',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='edits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
