# Generated by Django 4.0.4 on 2022-06-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_page_name_alter_blog_edits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopularBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('blog', models.ManyToManyField(to='blog.blog')),
            ],
        ),
    ]
