# Generated by Django 4.0.4 on 2022-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
