# Generated by Django 3.2.8 on 2023-01-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_schema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.RemoveField(
            model_name='mostpopularblog',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.DeleteModel(
            name='MostPopularBlog',
        ),
    ]
