# Generated by Django 3.2.8 on 2022-06-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='canonical',
            field=models.CharField(default='https://website.com/', max_length=900),
        ),
    ]
