# Generated by Django 3.2.8 on 2022-06-10 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_aboutpage_canonical'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='og_site',
            field=models.CharField(default=django.utils.timezone.now, max_length=156),
            preserve_default=False,
        ),
    ]
