# Generated by Django 3.2.8 on 2022-06-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_aboutpage_og_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='why_choose_us_img',
            field=models.ImageField(blank=True, null=True, upload_to='Page Data'),
        ),
    ]
