# Generated by Django 3.2.8 on 2022-06-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_aboutpage_why_choose_us_img_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('fb', models.CharField(max_length=156)),
                ('insta', models.CharField(max_length=156)),
                ('twitter', models.CharField(max_length=156)),
                ('youtube', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('review', models.TextField()),
            ],
        ),
    ]
